#!/usr/bin/env bash
# dev-setup.sh — One-command developer onboarding for consumer-ordering.
# Usage: ./scripts/dev-setup.sh [developer-name]
#
# This script:
#   1. Checks prerequisites (Docker, AWS CLI, Java 21, Node.js, Terraform)
#   2. Verifies AWS credentials
#   3. Runs Terraform to provision infrastructure + IAM user
#   4. Extracts outputs into a .env file
#   5. Seeds DynamoDB with sample data
#   6. Validates AWS access
#   7. Prints next steps

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TF_DIR="$PROJECT_ROOT/infrastructure/environments/dev"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

info()  { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error() { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# ========================
# Parse arguments
# ========================

DEVELOPER_NAME="${1:-}"
if [[ -z "$DEVELOPER_NAME" ]]; then
  echo "Usage: $0 <developer-name>"
  echo "  Example: $0 rohit"
  exit 1
fi

info "Setting up developer environment for: $DEVELOPER_NAME"

# ========================
# 1. Check prerequisites
# ========================

info "Checking prerequisites..."

check_command() {
  if ! command -v "$1" &> /dev/null; then
    error "$1 is not installed. $2"
  fi
}

check_command docker "Install Docker Desktop: https://www.docker.com/products/docker-desktop"
check_command aws "Install AWS CLI: https://docs.aws.amazon.com/cli/latest/userguide/install-cliv2.html"
check_command terraform "Install Terraform: https://developer.hashicorp.com/terraform/install"
check_command java "Install Java 21: https://adoptium.net/"
check_command node "Install Node.js: https://nodejs.org/"

# Check Java version
JAVA_VERSION=$(java -version 2>&1 | head -1 | cut -d'"' -f2 | cut -d'.' -f1)
if [[ "$JAVA_VERSION" -lt 21 ]]; then
  warn "Java 21+ recommended (found Java $JAVA_VERSION)"
fi

info "All prerequisites satisfied."

# ========================
# 2. Verify AWS credentials
# ========================

info "Verifying AWS credentials..."

if ! aws sts get-caller-identity &> /dev/null; then
  error "AWS credentials not configured. Run 'aws configure' first."
fi

AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
info "Authenticated to AWS account: $AWS_ACCOUNT_ID"

# ========================
# 3. Run Terraform
# ========================

info "Initializing Terraform..."
cd "$TF_DIR"
terraform init -input=false

info "Applying Terraform (provisioning infrastructure + IAM user)..."
terraform apply -input=false -auto-approve \
  -var="developers=[\"$DEVELOPER_NAME\"]"

# ========================
# 4. Generate .env file
# ========================

info "Extracting Terraform outputs..."

COGNITO_USER_POOL_ID=$(terraform output -raw cognito_user_pool_id)
COGNITO_CLIENT_ID=$(terraform output -raw cognito_client_id)
DYNAMODB_USERS_TABLE=$(terraform output -raw dynamodb_users_table)
DYNAMODB_PLANS_TABLE=$(terraform output -raw dynamodb_plans_table)
DYNAMODB_ORDERS_TABLE=$(terraform output -raw dynamodb_orders_table)
SQS_ORDER_EVENTS_QUEUE_URL=$(terraform output -raw sqs_order_events_queue_url)
AWS_REGION=$(terraform output -raw aws_region)

# Extract developer IAM credentials
DEV_ACCESS_KEY_ID=$(terraform output -json iam_developer_access_keys | jq -r ".\"$DEVELOPER_NAME\".access_key_id")
DEV_SECRET_ACCESS_KEY=$(terraform output -json iam_developer_access_keys | jq -r ".\"$DEVELOPER_NAME\".secret_access_key")

if [[ "$DEV_ACCESS_KEY_ID" == "null" || -z "$DEV_ACCESS_KEY_ID" ]]; then
  error "Failed to extract IAM credentials for $DEVELOPER_NAME"
fi

cd "$PROJECT_ROOT"

# Back up existing .env
if [[ -f .env ]]; then
  BACKUP=".env.backup.$(date +%Y%m%d%H%M%S)"
  warn "Existing .env found — backing up to $BACKUP"
  cp .env "$BACKUP"
fi

info "Writing .env file..."

cat > .env << EOF
# Auto-generated by dev-setup.sh for developer: $DEVELOPER_NAME
# Generated: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# AWS credentials (IAM user: consumer-ordering-dev-$DEVELOPER_NAME)
AWS_REGION=$AWS_REGION
AWS_ACCESS_KEY_ID=$DEV_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=$DEV_SECRET_ACCESS_KEY

# Cognito
COGNITO_USER_POOL_ID=$COGNITO_USER_POOL_ID
COGNITO_CLIENT_ID=$COGNITO_CLIENT_ID

# DynamoDB
DYNAMODB_USERS_TABLE=$DYNAMODB_USERS_TABLE
DYNAMODB_PLANS_TABLE=$DYNAMODB_PLANS_TABLE
DYNAMODB_ORDERS_TABLE=$DYNAMODB_ORDERS_TABLE

# SQS
SQS_ORDER_EVENTS_QUEUE_URL=$SQS_ORDER_EVENTS_QUEUE_URL
EOF

info ".env file created successfully."

# ========================
# 5. Seed data
# ========================

info "Seeding DynamoDB with sample plans..."

# Source .env so seed script picks up the right credentials
set -a
source .env
set +a

bash "$SCRIPT_DIR/seed-data.sh"

# ========================
# 6. Validate access
# ========================

info "Validating AWS access with developer credentials..."

# Test DynamoDB
if aws dynamodb describe-table \
  --table-name "$DYNAMODB_PLANS_TABLE" \
  --region "$AWS_REGION" \
  --no-cli-pager &> /dev/null; then
  info "DynamoDB access: OK"
else
  warn "DynamoDB access: FAILED (check IAM permissions)"
fi

# Test Cognito
if aws cognito-idp describe-user-pool \
  --user-pool-id "$COGNITO_USER_POOL_ID" \
  --region "$AWS_REGION" \
  --no-cli-pager &> /dev/null; then
  info "Cognito access: OK"
else
  warn "Cognito access: FAILED (check IAM permissions)"
fi

# Test SQS
if aws sqs get-queue-attributes \
  --queue-url "$SQS_ORDER_EVENTS_QUEUE_URL" \
  --attribute-names QueueArn \
  --region "$AWS_REGION" \
  --no-cli-pager &> /dev/null; then
  info "SQS access: OK"
else
  warn "SQS access: FAILED (check IAM permissions)"
fi

# ========================
# 7. Next steps
# ========================

echo ""
echo "========================================"
info "Setup complete!"
echo "========================================"
echo ""
echo "Your .env file has been configured with:"
echo "  - IAM user: consumer-ordering-dev-$DEVELOPER_NAME"
echo "  - Cognito, DynamoDB, and SQS credentials"
echo "  - Sample plan data seeded"
echo ""
echo "Next steps:"
echo "  1. Start all services:  docker compose up -d --build"
echo "  2. Open the app:        http://localhost:3000"
echo "  3. View logs:           docker compose logs -f"
echo ""
